import streamlit as st
import json

st.set_page_config(page_title="AutoCloudOps Dashboard", layout="wide")

st.title("AutoCloudOps – AI Cloud Optimization Dashboard")

st.write("Monitoring and optimizing cloud infrastructure using AI agents.")

# Sample cloud metrics (simulated data)
cloud_resources = [
    {"Instance": "EC2-1", "CPU Usage": 10, "Memory Usage": 20, "Status": "Idle"},
    {"Instance": "EC2-2", "CPU Usage": 75, "Memory Usage": 60, "Status": "Active"},
    {"Instance": "EC2-3", "CPU Usage": 15, "Memory Usage": 25, "Status": "Underutilized"},
]

st.subheader("Cloud Resource Metrics")

st.table(cloud_resources)

st.subheader("Detected Optimization Opportunities")

recommendations = [
    "EC2-1 is idle → consider stopping the instance",
    "EC2-3 is underutilized → downgrade instance type",
    "EC2-2 usage normal → no action required"
]

for r in recommendations:
    st.write("✅", r)

st.subheader("Estimated Cost Impact")

st.metric("Potential Monthly Savings", "$120")

st.info("Recommendations generated by AutoCloudOps Agentic AI system.")
